# Generated by Django 5.2.7 on 2026-01-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='ชื่อเล่น')),
                ('avatar', models.TextField(blank=True, default='', verbose_name='รูปโปรไฟล์ (Base64)')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('id_card_number', models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('position', models.CharField(choices=[('MANAGER', 'ผู้จัดการ/เจ้าของ (A2)'), ('STAFF', 'พนักงานทั่วไป (A1)')], default='STAFF', max_length=10, verbose_name='ตำแหน่ง')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
