# Generated by Django 5.2.7 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('MANAGER', 'ผู้จัดการ/เจ้าของ'), ('STAFF', 'พนักงานทั่วไป')], default='STAFF', max_length=10, verbose_name='ตำแหน่ง'),
        ),
    ]
