# Generated by Django 5.2.7 on 2026-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_id_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('MANAGER', 'พนักงาน')], default='MANAGER', max_length=10, verbose_name='ตำแหน่ง'),
        ),
    ]
