# Generated by Django 5.2.7 on 2025-12-08 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อร้านค้า/บริษัท')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='รหัสสินค้า (SKU)')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วยนับ')),
                ('pieces_per_unit', models.IntegerField(default=1, verbose_name='จำนวนชิ้นย่อย (Pack Size)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาทุนปัจจุบัน')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาขาย')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาขายส่ง')),
                ('compatible_models', models.CharField(blank=True, max_length=255, verbose_name='รุ่นรถที่ใช้ได้')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='หมวดหมู่')),
                ('primary_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='ร้านประจำ')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='คงเหลือ')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='จุดสั่งซื้อเพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่เอกสาร')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ซื้อ')),
                ('status', models.CharField(choices=[('DRAFT', 'ร่าง'), ('POSTED', 'ยืนยันรับของ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม')),
                ('remark', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplier', verbose_name='ซื้อจาก')),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวน')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ทุนต่อหน่วย (บาท)')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='เลขที่บิล')),
                ('sale_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดสุทธิ')),
                ('status', models.CharField(choices=[('DRAFT', 'ร่าง'), ('POSTED', 'ขายแล้ว'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='DRAFT', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'เงินสด'), ('TRANSFER', 'โอนเงิน')], default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ยอดเงิน')),
                ('status', models.CharField(choices=[('PENDING', 'รอตรวจสอบ'), ('CONFIRMED', 'ยืนยันแล้ว'), ('VOID', 'ยกเลิก')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.sale')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ราคาขาย')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ต้นทุน')),
                ('stock_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ตัดสต็อกจริง')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.sale')),
            ],
            options={
                'db_table': 'sale_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'รับเข้า'), ('OUT', 'ขายออก'), ('ADJ', 'ปรับยอด')], db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนที่ขยับ')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ทุนตอนนั้น')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='คงเหลือหลังทำรายการ')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='อ้างอิงเอกสาร')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
