# Generated by Django 5.2.7 on 2025-12-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินทอน'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินที่รับ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนลด'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ยอดที่ต้องชำระ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'เงินสด'), ('qr', 'QR Code'), ('transfer', 'โอนเงิน')], default='cash', max_length=20, verbose_name='วิธีชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('confirmed', 'ยืนยันแล้ว'), ('void', 'ยกเลิก')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='ซัพพลายเออร์'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รวม'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='stock_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ตัดสต็อก (ชิ้น)'),
        ),
    ]
