# Generated by Django 5.2.7 on 2025-12-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_payment_options_payment_change_payment_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='pieces_per_unit',
        ),
    ]
