# Generated by Django 5.2.7 on 2025-12-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='stock_deducted',
        ),
    ]
