# Generated by Django 5.2.7 on 2025-12-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_saleitem_stock_deducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='min_quantity',
        ),
    ]
