# Generated by Django 5.2.7 on 2025-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_inventory_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='คงเหลือ'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
