# Generated by Django 5.2.7 on 2025-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='doc_type',
            field=models.CharField(choices=[('SALE', 'บิลขายปกติ'), ('RETURN', 'ใบลดหนี้/รับคืน')], db_index=True, default='SALE', max_length=10, verbose_name='ประเภทเอกสาร'),
        ),
        migrations.AddField(
            model_name='sale',
            name='ref_doc_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='อ้างอิงเลขที่บิลเดิม'),
        ),
    ]
