# Generated by Django 5.2.7 on 2025-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sale_doc_type_sale_ref_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='doc_type',
            field=models.CharField(choices=[('SALE', 'บิลขายปกติ'), ('RETURN', 'รับคืน')], db_index=True, default='SALE', max_length=10, verbose_name='ประเภทเอกสาร'),
        ),
    ]
