# Generated by Django 5.2.7 on 2025-12-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockmovement_note_alter_sale_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('HOLD', 'พักบิล'), ('DRAFT', 'ร่าง'), ('POSTED', 'ขายแล้ว'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
