# Generated by Django 5.2.7 on 2026-01-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('HOLD', 'พักบิล'), ('POSTED', 'ขายแล้ว'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
