# Generated by Django 5.2.7 on 2026-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_sale_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='items_per_purchase_unit',
            field=models.IntegerField(default=1, verbose_name='จำนวนชิ้นต่อหน่วยซื้อ'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12, verbose_name='สต็อกขั้นต่ำ'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='หน่วยซื้อ'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดที่ต้องชำระ'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('HOLD', 'พักบิล'), ('POSTED', 'ขายแล้ว'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='HOLD', max_length=20),
        ),
    ]
