# Generated by Django 5.2.7 on 2026-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_options_remove_stockmovement_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='สต็อกขั้นต่ำ'),
        ),
    ]
