# Generated by Django 5.2.7 on 2026-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12, verbose_name='สต็อกขั้นต่ำ'),
        ),
    ]
