# Generated by Django 5.2.7 on 2026-01-19 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_min_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='SaleItem',
            new_name='TransactionItem',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='sale',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transactionitem',
            old_name='sale',
            new_name='transaction',
        ),
    ]
