# Generated by Django 5.2.7 on 2026-01-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_sale_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-TransactionItem_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sale_date',
            new_name='TransactionItem_date',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='TransactionItem',
        ),
        migrations.AlterModelTable(
            name='transactionitem',
            table='Transaction_items',
        ),
    ]
