# Generated by Django 5.2.7 on 2026-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_partial_sale',
            field=models.BooleanField(default=True, verbose_name='อนุญาตให้แบ่งขาย'),
        ),
    ]
