# Generated by Django 5.2.7 on 2026-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_allow_partial_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='actual_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เพิ่มสต็อก (ชิ้น)'),
        ),
    ]
