# Generated by Django 5.2.7 on 2026-01-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_purchaseitem_actual_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_type',
            field=models.CharField(choices=[('SAME', 'เหมือนกันหมด'), ('L-R', 'ซ้าย-ขวา'), ('F-R', 'หน้า-หลัง')], default='SAME', max_length=10, verbose_name='ประเภทชุด'),
        ),
    ]
