# Generated by Django 5.2.7 on 2026-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_bundle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
