# Generated by Django 5.2.7 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_bundle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='bundle_items',
            field=models.JSONField(blank=True, null=True, verbose_name='รายการสินค้าในชุด'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='display_sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='SKU ที่แสดง'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='sale_unit',
            field=models.CharField(default='ชิ้น', max_length=20, verbose_name='หน่วยขาย'),
        ),
    ]
