# Generated by Django 5.2.7 on 2026-01-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_transactionitem_bundle_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='sale_unit',
            new_name='unit_type',
        ),
    ]
