# Generated by Django 5.2.7 on 2026-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_sale_unit_transactionitem_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อสินค้า (กลาง)'),
        ),
    ]
