# Generated by Django 5.2.7 on 2026-01-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_base_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionItem_date',
            new_name='transaction_date',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
