# Generated by Django 5.2.7 on 2026-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_components',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='สินค้าในชุด (Components)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, verbose_name='เป็นสินค้าชุด'),
        ),
    ]
