# Generated by Django 5.2.7 on 2026-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='GEN', max_length=10, verbose_name='รหัสย่อ (3 ตัวอักษร)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
    ]
