# Generated by Django 5.2.7 on 2026-02-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_category_options_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default='GEN', max_length=10, unique=True, verbose_name='รหัสย่อ (3 ตัวอักษร)'),
        ),
    ]
